import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from '@mui/material/Link';
import Container from '@mui/material/Container';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.jsテストサイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.jsテストサイト
        </h1>

        <Container>
          <div className={styles.link_area}>
            <div className={styles.about_link}>
              <Link href="/test">テストページ</Link>
            </div>
            <div className={styles.blog_link}>
              <Link href="/blog">Blog</Link>
            </div>
            <div className={styles.blog_link}>
              <Link href="/apiTest">API</Link>
            </div>
            <div className={styles.blog_link}>
              <Link href="/indexedDB">IndexedDB</Link>
            </div>
          </div>
        </Container>
      </main>

      <footer className={styles.footer}>
        Powered by Mizukazu
      </footer>
    </div>
  )
}
