import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from '@mui/material/Link';
import { Container, Grid } from '@mui/material';
import { useCallback, useMemo } from 'react';
import { ReactDraftWysiwyg } from '../components/ReactDraftWysiwyg';

export default function Home() {
  const a = 10;
  const b = 5;

  /** 結果の値を返す */
  const sampleFuncMemo = useMemo(() => {
    return a + b;
  },[a, b])

  /** 関数を返す */
  const sampleFuncCallback = useCallback(() => {
    return a + b;
  },[a, b])

  const AddResult = () => (<div>計算結果: {sampleFuncCallback()}</div>)

  console.log(sampleFuncMemo);
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.jsテストサイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Next.jsテストサイト
        </h1> */}

        <h1 className='test mb-5'>
          Next.jsテストサイト
        </h1>

        <Container>
          <Grid container spacing={2} className={styles.link_area}>
            <Grid item md={4} className={styles.about_link}>
              <Link href="/test">テストページ</Link>
            </Grid>
            <Grid item md={3} className={styles.blog_link}>
              <Link href="/blog">Blog</Link>
            </Grid>
            <Grid item md={2} className={styles.blog_link}>
              <Link href="/apiTest">API</Link>
            </Grid>
            <Grid item md={3} className={styles.blog_link}>
              <Link href="/indexedDB">IndexedDB</Link>
            </Grid>
          </Grid>
          <Grid container spacing={2} className={styles.link_area}>
            <Grid item md={4} className={styles.about_link}>
              <Link href="/qrcode">QRコードテスト</Link>
            </Grid>
            <Grid item md={4} className={styles.about_link}>
              <Link href="/antdesign">AntDesignテスト</Link>
            </Grid>
          </Grid>
          <Grid container spacing={2} className={styles.link_area} style={{marginTop: 60}}>
            <AddResult />
          </Grid>
          <Grid container spacing={2} className={styles.link_area} style={{marginTop: 60}}>
            <ReactDraftWysiwyg />
          </Grid>
        </Container>
      </main>

      <footer className={styles.footer}>
        Powered by Mizukazu
      </footer>
    </div>
  )
}